- project:
    name: jluk-codi-org/sampleproject
    check:
      jobs:
        - noop
        - echo

- job:
    name: timeout
    run: timeout.yaml

- job:
    name: echo
    required-projects:
      - jluk-codi-org/anotherproject
    run: echo.yaml
